spring:
  main:
    banner-mode: 'off'
  application:
    name: 'es-sample'
  elasticsearch:
    rest:
      uris: 'localhost:9200'

logging:
  level:
    org.springframework.data.elasticsearch.client.WIRE: trace

management:
  endpoint:
    health:
      show-details: always

server:
  error:
    include-stacktrace: never